### ISSUE TITLE
Build flatpaks for wider Linux support

### ISSUE THREAD

**Issue by PowerBall253** [New-Club-Penguin/NewCP-App#10]
Since Electron Forge is being used to build the binaries, the [Flatpak maker](https://www.electronforge.io/config/makers/flatpak) could be added to have compatibility with all major Linux distros without having to provide a separate package for each one.

**Comment by Bale001** [comment]
Hi, thank you for this suggestion.

I have created a pre-release of the client that comes with a flatpak binary. I don't have a linux machine, so please let me know if it works: https://github.com/New-Club-Penguin/NewCP-App-Build/releases/tag/v1.5.1

Thank you!

**Comment by brunoanc** [comment]
Hi, thanks for the quick response!
I installed it on my machine without issues, seems to work perfectly. Thank you!
