### ISSUE TITLE
Malware Signatures (Mostly AI detections but some are concerning)

### ISSUE THREAD

**Issue by averadian** [New-Club-Penguin/NewCP-App#33]
Please explain:

v1.4.3: 
[VirusTotal](https://www.virustotal.com/gui/file/1f4fbd5fdc042a49cabd5790f20285a9a1f01c0e7c3098b80062a242eea306c9/detection)
[Triage](https://tria.ge/240405-t5eb9sha6v)

v1.5.1: 
[VirusTotal](https://www.virustotal.com/gui/file/8beb241bb435e85b7d8972082aaa79255fce8216b05d750d5863386b38ba18b5/detection)
[Triage](https://tria.ge/240405-vhdmwshd9s)

v1.5.2: 
[VirusTotal](https://www.virustotal.com/gui/file/8d3e4f9595994ef187124a5ad76a5462fc212e6c4180b70304d0ac9f0960616e/detection)

v1.6.0: 
[VirusTotal](https://www.virustotal.com/gui/file/96d1b1da7ded0498c1e591e3673018eb24f7370cbd0a22325da6d95a68eeec18/detection)

v1.6.1: [VirusTotal](https://www.virustotal.com/gui/file/abc161b975d50f5411184c10bcebf28fda9c69294423d1f0681aef8db5627e42/detection)
[Triage](https://tria.ge/240408-q34btsae55)

Also if you could shed light on this as well:
`C:\Windows\SysWOW64\7za.exe C:\Windows\System32\7za.exe" x -pinfected -y -o"C:\Users\user\AppData\Local\Temp\hqy5lnj2.lqt" "C:\Users\user\Desktop\download.zip`

**Comment by AllinolCP** [comment]
Thank You, However the detection seems to be coming from
https://github.com/medikoo/es5-ext/issues/186
It is out of our scope, and it just seems to be sending messages and does not harm your computer.

**Comment by iContinux** [comment]
This was cleared up via discord ticket and was linked to - https://github.com/medikoo/es5-ext/issues/186

For future inquires into issues such as these, please open a support ticket via discord, rather than an issue here.
